apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: tailscale
  name: tailscale
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale
    spec:
      serviceAccountName: tailscale
      containers:
      - name: tailscale
        imagePullPolicy: Always
        image: monachus/tailscale:v1.16
        env:
        # Store the state in a k8s secret
        - name: KUBE_SECRET
          value: tailscale-auth
        - name: USERSPACE
          value: "true"
        - name: AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: AUTH_KEY
              optional: false
        - name: ROUTES
          value: "10.73.0.0/16,10.72.0.0/16"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
