bases:
- ../normal
namePrefix: poly-
commonLabels:
  app.kubernetes.io/name: poly-wp-test
  environment: polyscripted
patchesStrategicMerge:
- patches/deployment-image.yaml
- patches/configmap.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: wp-test
  path: patches/mountPath.yaml
- target:
    group: gateway.solo.io
    version: v1
    kind: VirtualService
    name: wp-test
  path: patches/virtualservice.yaml
