apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-demo-productionwebsite-com
  namespace: traefik-demo
spec:
  dnsNames:
  - traefik-demo.productionwebsite.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: traefik-demo-productionwebsite-com-crt
