apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-demo-edge
  namespace: traefik-system
spec:
  dnsNames:
  - traefik-demo.edge.138.197.212.50.sslip.io
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: traefik-demo-edge-crt
